language: go
branches:
    only:
    - master
    - /v\d+\.\d+\.\d+/
env:
 - GO111MODULE=on
go_import_path: https://github.com/pligrim/surfboard
matrix:
  fast_finish: true
  include:
  - go: '1.12'
    name: Deployment
    before_deploy:
    - CGO_ENABLED=0 GOARCH=386 go build  -ldflags="-s -w" -o "surfboard_i386"
    - CGO_ENABLED=0 GOARCH=amd64 go build  -ldflags="-s -w" -o "surfboard_amd64"
    deploy:
      provider: releases
      api_key: $gitkey
      file_glob: true
      file: surfboard_*
      skip_cleanup: true
      on:
        tags: true
        repo: pligrim/surfboard
        branch: master
